<?php

    class AMenu extends Menu
    {
        const  AMenu_LABEL_ACTIVE = 'Kích hoạt';
        const  AMenu_LABEL_INACTIVE = 'Ẩn';

        /**
         * @return array validation rules for model attributes.
         */
        public function rules()
        {
            // NOTE: you should only define rules for those attributes that
            // will receive user inputs.
            return array(
                array('type_menu, created_at', 'required'),
                array('parent_id, type_menu, ordering, status', 'numerical', 'integerOnly' => true),
                array('title, link', 'length', 'max' => 255),
                // The following rule is used by search().
                // @todo Please remove those attributes that should not be searched.
                array('id, parent_id, type_menu, title, link, ordering, status, created_at', 'safe', 'on' => 'search'),
            );
        }

        /**
         * @return array relational rules.
         */
        public function relations()
        {
            // NOTE: you may need to adjust the relation name and the related
            // class name for the relations automatically generated below.
            return array(
                'parent_menu' => array(self::BELONGS_TO, 'AMenu', 'parent_id'),
                'sub_menu'    => array(self::HAS_MANY, 'AMenu', 'parent_id'),
            );
        }

        /**
         * @return array customized attribute labels (name=>label)
         */
        public function attributeLabels()
        {
            return array(
                'id'         => 'ID',
                'parent_id'  => 'Danh mục cha',
                'type_menu'  => 'Kiểu menu',
                'title'      => 'Tên Menu',
                'link'       => 'Link',
                'ordering'   => 'Thứ tự',
                'status'     => 'Trạng thái',
                'created_at' => 'Created At',
            );
        }

        /**
         * Retrieves a list of models based on the current search/filter conditions.
         *
         * Typical usecase:
         * - Initialize the model fields with values from filter form.
         * - Execute this method to get CActiveDataProvider instance which will filter
         * models according to data in model fields.
         * - Pass data provider to CGridView, CListView or any similar widget.
         *
         * @return CActiveDataProvider the data provider that can return the models
         * based on the search/filter conditions.
         */
        public function search()
        {
            // @todo Please modify the following code to remove attributes that should not be searched.

            $criteria = new CDbCriteria;

            $criteria->compare('id', $this->id);
            $criteria->compare('parent_id', $this->parent_id);
            $criteria->compare('type_menu', $this->type_menu);
            $criteria->compare('title', $this->title, true);
            $criteria->compare('link', $this->link, true);
            $criteria->compare('ordering', $this->ordering);
            $criteria->compare('status', $this->status);
            $criteria->compare('created_at', $this->created_at, true);

            return new CActiveDataProvider($this, array(
                'criteria' => $criteria,
            ));
        }

        /**
         * Returns the static model of the specified AR class.
         * Please note that you should have this exact method in all your CActiveRecord descendants!
         * @param string $className active record class name.
         * @return Menu the static model class
         */
        public static function model($className = __CLASS__)
        {
            return parent::model($className);
        }

        public static function getStatusList()
        {
            return array(
                self::ACTIVE   => 'Đã duyệt',
                self::INACTIVE => 'Ẩn',
            );
        }


        public function beforeValidate()
        {
            if($this->isNewRecord){
                $this->created_at = date('Y-m-d H:i:s');
            }
            return parent::beforeValidate(); // TODO: Change the autogenerated stub
        }
    }
